export const UPDATE_BASE_URL_BY_ID_TYPE = 'UPDATE_BASE_URL_BY_ID_TYPE';

export const UPDATE_CURRENT_URL = 'UPDATE_CURRENT_URL';

export const UPDATE_CURRENT_TAB_ID = 'UPDATE_CURRENT_TAB_ID';

export const UPDATE_STATE_BY_URL = 'UPDATE_STATE_BY_URL';

export const UPDATE_LOCKED_URL_STATE = 'UPDATE_LOCKED_URL_STATE';

export const UPDATE_IS_VUEX_LOADED = 'UPDATE_IS_VUEX_LOADED';

export const UPDATE_DOI_COUNT_BY_TAB_ID = 'UPDATE_DOI_COUNT_BY_TAB_ID';

export const UPDATE_ERROR_MESSAGE = 'UPDATE_ERROR_MESSAGE';

export const UPDATE_IS_HIGHLIGHTED = 'UPDATE_IS_HIGHLIGHTED';

export const UPDATE_HIGHLIGHT_COLOR = 'UPDATE_HIGHLIGHT_COLOR';

export const UPDATE_FONT_COLOR = 'UPDATE_FONT_COLOR';